	;	Miscellaneous rules.

cr							=	%x0D

lf							=	%x0A

crlf						=	cr lf / lf
								;in this abnf the CRLF is not standard.

sp							=	%x20

htab						=	%x09

wsp							=	sp / htab

c-wsp						=	1*(wsp / crlf)

high-alpha					=	%x41-5A

low-alpha					=	%x61-7A

alpha						=	high-alpha / low-alpha

digit						=	%x30-39

safe						=	"$" / "-" / "_" / "." / "+"

extra						=	"!" / "*" / "'" / "(" / ")" / ","

national					=	"{" / "}" / "|" / "\" / "^" / "~" / "[" / "]" / "`"

punctuation					=	"<" / ">" / "#" / "%" / %x22 
								; the %x22 is just the double quote.

reserved					=	";" / "/" / "?" / ":" / "@" / "&" / "="

hex-digit					=	digit / %x41-46 / %x61-66

unreserved					=	alpha / digit / safe / extra

uchar						=	unreserved / escape

xchar						=	unreserved / reserved / escape

pct-encoded					=	"%" hex-digit hex-digit

sub-delims					=	"!" / "$" / "&" / "'" / "(" / ")" 
							=/	"*" / "+" / "," / ";" / "="

pchar						=	unreserved / pct-encoded / sub-delims / ":" / "@"

number						=	1*digit

hex-number					=	1*hex-digit

prefixed-number				=	number
							=/	"0x" 1*hex-digit
							=/	"0b" 1*("0" / "1")



	;	url rules (here is only considerd the case of http uri).
fragment					=	*(pchar / "/" / "?")

query						=	*(pchar / "/" / "?")

segment						=	*pchar

path						=	*("/" segment)

port						=	":" number

reg-name					=	*(unreserved / pct-encoded / sub-delims)

ipv6						=	;	lets supose that this magically works.
							;	"[" hex-number 15(":" hex-number) "]"
							;=/	"[" "::" hex-number *15(":" hex-number) "]"

ipv4						=	number "." number "." number "." number

ip							=	ipv4
							=/	ipv6

host						=	ip / reg-name

authority					=	host *1port

http-scheme-symbol			=	"http"

scheme						=	http-scheme-symbol

url							=	scheme ":" authority path *1("?" query) *1("#" fragment)

	;	some location rules.
index						=	"index" 1*(c-wsp path) *1c-wsp ";"

auto-index					=	"auto_index" c-wsp ("yes" / "no") *!c-wsp ";"

root						=	"root" c-wsp path *1c-wsp ";"

return						=	"return" c-wsp number c-wsp (url / path) *1c-wsp ";"

method						=	"get"
							=/	"head"
							=/	"post"
							=/	"put"
							=/	"delete"
							=/	"connect"
							=/	"options"
							=/	"trace"
							=/	"patch"

methods-allowed-symbol		=	"methods_allowed"

methods-allowed				=	methods-allowed-symbol 1*(c-wsp method) *1c-wsp ";"

	;	location rules.
location-directive			=	location
							=/	return
							=/	methods-allowed
							=/	root
							=/	auto-index
							=/	index


location-symbol				=	"location"

location					=	location-symbol c-wsp path
								c-wsp "{"
								1*(*1c-wsp location-directive)
								*1c-wsp "}"

	;	somme server directives rules.
size-unit					=	"B"
							=/	"KB"
							=/	"MB"
							=/	"GB"
							=/	"TB"
							=/	"PB"

file-size					=	"0"
							=/	number size-unit

client-max-body-size-symbol	=	"client_max_body_size"

client-max-body-size		=	client-max-body-size-symbol c-wsp file-size *1c-wsp ";"

error-code					=	number

error-page-symbol			=	"error_page"

error-page					=	error-page-symbol 1*(c-wsp error-code) c-wsp path *1c-wsp ";"

socket						=	ip
							=/	ip port
							=/	port
								;	this soket will alwais use http (tcp)

listen-symbol				=	"listen"

listen						=	listen-symbol 1*(c-wsp socket) *1c-wsp ";"

server-name-symbol			=	"server_name"

server-name					=	server-name-symbol 1*(c-wsp reg-name) *1c-wsp ";"

	;	server rules.
server-directive			=	server-name
							=/	listen
							=/	error-page
							=/	client-max-body-size
							=/	location


server-symbol				=	"server"

server						=	*1c-wsp server-simbol
								*1c-wsp "{"
								1*(*1c-wsp server-directive)
								*1c-wsp "}" *1c-wsp

