	;	Miscellaneous rules.

cr							=	%x0D

lf							=	%x0A

crlf						=	cr lf / lf
								;in this abnf the CRLF is not standard.

sp							=	%x20

htab						=	%x09

wsp							=	sp / htab

c-wsp						=	1*(wsp / crlf)

high-alpha					=	%x41-5A

low-alpha					=	%x61-7A

alpha						=	high-alpha / low-alpha

digit						=	%x30-39

hex-digit					=	digit / %x41-46 / %x61-66

safe						=	"-" / "_" / "."

sub-delims					=	"!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / "="

pct-encoded					=	"%" hex-digit hex-digit
									; used to encode character that are alredy in use like the "{"

	;	all the lexeme rules.
c-wsp						=	1*(wsp / crlf)

control-character			=	"{" / "}" / ";"

number						=	1*digit

key-words					=	"server"
							=/	"server_name"
							=/	"listen"
							=/	"error_page"
							=/	"client_max_body_size"
							=/	"location"
							=/	"return"
							=/	"limit_exept"
							=/	"root"
							=/	"auto_index"
							=/	"index"

text						=	1*(alpha / digit)
							=/	name
							=/	pct-encoded
							=/	%x22 *(%x01-ff) %x22 ; text delimited with double quotes
							;	any character that dosent fit in any othe lexeme.

	;	rules.
	;	server directives.
return						=	"return" c-wsp number c-wsp text *1c-wsp ";"
									; the number is just a status code.
									; and the text can be a uri or just plain text.
									; refer to the statuc codes, uri abnf.

client-max-body-size		=	"client_max_body_size" c-wsp text *1c-wsp ";"
									; the text is just a file size.
									; refer to the size abnf.

error-page					=	"error_page" 1*(c-wsp status-code-error) c-wsp path *1c-wsp ";"

socket						=	ip
							=/	ip port
							=/	port
								;	this soket will alwais use http (tcp)

listen						=	"listen" 1*(c-wsp socket) *1c-wsp ";"

server-name					=	"server-name" 1*(c-wsp reg-name) *1c-wsp ";"

	;	server rules.
server-directive			=	server-name
							=/	listen
							=/	error-page
							=/	client-max-body-size
							=/	location
							=/	return

server						=	*1c-wsp "server"
								*1c-wsp "{"
								1*(*1c-wsp server-directive)
								*1c-wsp "}" *1c-wsp

